pciutils/pciutils

lib/hurd.c

I've fixed a bug that produced a memory violation, and also made the module compile again since `a` was undefined in `device_port_lookup`

Hurd: bug fixes and compile again

---

Makefile

Without this change, the build will fail when it cannot find `libpci.pc`.

Makefile: fix for parallel builds (make -j)

---

Makefile

The `install-lib` target results in a broken installation because it only symlinks `libpci.so` to `libpci.so.$(ABI_VERSION)`, but `libpci.so.$(ABI_VERSION)` does not exist. This PR adds the missing symlink between `libpci.so.$(ABI_VERSION)` and the actual library file.

add missing symlinks to libraries in install-lib target

---

lib/configure

Checking `/usr/include` for system library headers is insufficient for Darwin as `libresolv` and `zlib` ship with the macOS SDK. This patch simply uses `xcrun` to detect the current macOS SDK root and expands it when checking for the headers.

Fix the primitive system dependency discovery for Darwin systems

---

README.Windows
lib/i386-io-windows.h

This pull request improves i386-io-windows.h code:
* Fix support for pre-NT systems (no special code is needed, access to PCI I/O ports is always allowed).
* Fix compilation with older CRTDLL and new modern UCRT runtime libraries.
* Replace usage of license incompatible WinIO.dll library and requirement of having installed insecure 3rd-party kernel module WinIo.sys by NtSetInformationProcess(ProcessUserModeIOPL) syscall supported directly by NT kernels (equivalent of iopl(3) on Linux). Issuing NtSetInformationProcess(ProcessUserModeIOPL) syscall requires to have special NT privileges and this change also implements temporary privilege grants for the calling thread according to token access guidelines.
Differently compiled lspci.exe binaries were tested in VM on NT 3.51, NT 4.0, 98 SE, …

libpci: Improve i386-io-windows.h port

---

lib/configure
lib/init.c

With compile option PCI_PATH_IDS_DIR="" loads pci.ids on Windows from the executable directory.

libpci: For PCI_OS_WINDOWS allows to load pci.ids from executable directory

---

lib/header.h
ls-caps.c

As of PCIe 3.0, the LnkCtl2 "Compliance De-emphasis" field has been
renamed to "Compliance Preset/De-emphasis", and there are several new
bit encodings for various de-emphasis and preshoot combinations.
The name of the PCI_EXP_LNKCTL2_COM_DEEMPHASIS() macro is not changed
by this commit, as it is part of the libpci API.
Reported-by: Tim CC Chen(陳志佳) <Tim.CC.Chen@wnc.com.tw>
Signed-off-by: Lennert Buytenhek <buytenh@arista.com>

Add PCIe 3.0+ decoding of the LnkCtl2 Compliance Preset/De-emphasis field

---

lib/i386-ports.c

It is used as argument for intel_cleanup_io() function.

i386-ports: Do not mark pci_access in conf12_cleanup() as unused

---

lib/i386-io-windows.h

i386-ports.c: In function ‘conf12_setup_io’:
i386-io-windows.h:1021: warning: ‘old_token’ may be used uninitialized in this function
i386-io-windows.h:1021: note: ‘old_token’ was declared here
It is always properly initialized when accessed, just gcc compiler does not see it.

libpci: i386-io-windows.h: Mute false-positive warning

---

lib/i386-io-windows.h

There is no 64-bit version of CRTDLL library. MinGW-w64 provided bogus
64-bit import library for non-existent runtime DLL library, which was
recently deleted.

libpci: i386-io-windows.h: Fix comment about CRTDLL

---

lib/header.h
lspci.c

lspci sees header type with 0x7f value in case config space is not
accessible. It may be because of permission issues or missing backend
(e.g. on Windows) or because device itself does not respond to config
cycles and config space is inaccessible.
Inaccessible config space is common scenario for switchable PCIe GPU
cards. Some Nvidia and also some AMD cards when sleep then lspci sees
all-ones in their config space. But kernel has registered those cards and
some of their properties are cached ans available via sysfs or procfs (from
time when card was awake).
Currently lspci shows error message "Unknown header type 7f" and does not
parse any value neither from config space nor from sysfs backend.
So try to show at least information which kernel provided into libpci
struct pci_dev.
Set …

lspci: Show information also for devices with unknown header type

---

README
README.Windows
lib/Makefile
lib/configure
lib/emulated.c
lib/init.c
lib/internal.h
lib/pci.h
lib/win32-cfgmgr32.c
ls-map.c
ls-tree.c
lspci.c
lspci.h
pcilib.man

Access via cfgmgr32.dll library allows to list PCI devices and retrieve their basic properties and system resource configuration. Access is available to all users and should not require special privileges, access tokens, rights or permissions.
It works for both 32-bit and 64-bit systems. But there is a caveat, 32-bit application on 64-bit system cannot retrieve system resources.
Disadvantage of cfgmgr32.dll library that it does not provide access to PCI config space and so everything needs to be implemented via libpci properties.
Git branch linked to this pull request contains commits which extends libpci API/ABI for exporting useful PCI properties. I have also changes for lspci to use them and also implementations for sysfs and procfs providers, but these changes depends on other pending …

Add native windows implementation via cfgmgr32.dll library

---

ls-caps.c

Bridge PM and B3 were from "Power Management Control/Status Register", but should be from "PMCSR_BSE Bridge Support Extensions register"

Fix lspci: PMCSR PCI to PCI Bridge Support Extensions

---

lib/configure
lib/i386-io-windows.h
lib/init.c

* libpci: Compile windows i386-ports only for x86 CPU
* libpci: Always call pci_set_name_list_path() in pci_init_name_list_path()
* libpci: i386-io-windows.h: Fix MinGW build with pre-4.00 MSVCRT runtime library
* libpci: i386-io-windows.h: Fix error handling for GetProcessImageFileNameW() and GetModuleFileNameExW()

Various I/O port fixes for win32 code

---

lib/header.h
ls-ecaps.c

I wanted to help #59 along since it's been open for awhile and I'm interested in following up with additional CXL DVSEC decoding. I addressed the accessing cached config data by type-casting pointers issues by replacing them with their respective `get_conf_xxx` and rebased against the current master. Other than that, everything remains as originally written by @bwidawsk.

lspci: Improve CXL DVSEC decoding

---

lib/hurd.c

The hurdish methods only implement the region and base information, the
rest should be taken from the generic method.

hurd: fix filling information

---

lib/header.h

`HyperTransport / Host or Secondary Interface / Command Register / Device Number` mask should be 0b1111100 (0x007c), not 0b1110110 (0x0076).

lib: Fix PCI_HT_SEC_CMD_DN

---

lib/Makefile
lib/configure
lib/init.c
lib/internal.h
lib/pci.h
lib/win32-sysdbg.c
pcilib.man

NT SysDbg interface allow access to the PCI config space. Only devices on
the first domain are available and only first 256 bytes of the PCI config
space can be accessed. Compared to intel-conf1 access, this API is race
free as NT kernel serialize access to PCI I/O ports. This NT SysDbg API is
used by the !pci command of 32-bit WinDbg kernel debugger for displaying
PCI config space. Debug privilege is required to use this NT interface.

libpci: Add new windows NT sysdbg implementation

---

lib/configure

'which' is not required by POSIX and is an external command which may not be
available, and 'command -v' does the job just fine.
Debian and Gentoo at least are both making efforts to drop which from
their base system package list.
Signed-off-by: Sam James <sam@gentoo.org>

lib/configure: drop usage of which

---

lib/i386-io-windows.h

GCC header file <x86intrin.h> defines static inline function __readeflags()
which calls correct __builtin_ia32_readeflags_XX() builtin.
Header file <x86intrin.h> is included by MinGW-w64's <intrin.h> header file
in new versions of MinGW-w64 and <intrin.h> may be included transitionally
by some other header files automatically.
Defining __readeflags() as both macro and static inline function cause
compile errors.
Fix this compile error by not defining __readeflags() macro and instead
include GCC header file <x86intrin.h>.

libpci: i386-io-windows.h: Do not define __readeflags() for GCC 4.9+

---

Makefile
lib/Makefile
lib/configure
lib/dllrsrc.rc.in
lib/filter.c
lib/internal.h
lib/libpci.ver
lib/ver2def.pl

PE/COFF format, used by DLL libraries, does not support version symbols
like ELF format. Recommendation from Microsoft for DLL symbol versioning is
to use DLL API sets. But DLL API sets scheme requires for every API change
to generated a new slim forwarding DLL library, which is unsuitable for
distribution which wants just one DLL library with all version symbols.
So instead of Microsoft recommended scheme for DLL versioning, use new
different versioning scheme: Symbol is composed by function name, at (@)
character and version string (version is same as for ELF targets). Symbol
name without version information is added only into the DLL DEF file as
alias to symbol with higest version. So linker at application link time
resolves "unversioned" symbol to the versioned one via this alias and …

libpci: Add support for building versioned shared Windows DLL library libpci3.dll

---

lib/header.h
ls-ecaps.c

Fix decoding of register blocks by introducing offset to position calculation (8.1.9 of CXL 3.0 spec) and removed unused defines for Register Locator DVSEC. According to Figure 8-6 (8.1.9 of CXL 3.0 spec), Register Blocks are also indexed starting at 1. 
Signed-off-by: Jaxon Haws <jaxon.haws@amd.com>

cxl: Fix Register Locator DVSEC decoding

---

Makefile
lib/Makefile
lib/winrsrc.rc.in

Extend existing .in resource template file and generate resource objects also for lspci.exe and setpci.exe executables.

windows: Put name and version information into lspci/setpci executables

---

lib/i386-ports.c

Do not call pci_generic_block_read() and pci_generic_block_write() functions when io is locked. These functions call back same backend read/write function which tries to lock and unlock io again.

i386-ports: Fix intel_io_lock usage

---

lib/i386-io-windows.h

Show error message from intel_setup_io() function into debug area instead of error area. This is what other backends do as intel_setup_io() is called during quite detect phase, which may fail.
Also show human readable failure instead of magic code number.

libpci: i386-io-windows.h: Improve ProcessUserModeIOPL error message

---

lib/i386-io-linux.h

Since Linux 2.6.8, it is possible to use ioperm() syscall to gain access for all I/O ports. Because iopl() syscall before Linux 5.5 allowed userspace to disable interrupts, prefer usage of ioperm() syscall and ask for access only for PCI ports.

i386-io-linux: Prefer usage of ioperm()

---

lib/win32-cfgmgr32.c

NT namespace separator may be single or double backslash.

libpci: win32-cfgmgr32: Fix parsing paths in NT format

---

lib/Makefile
lib/aix-device.c
lib/configure
lib/generic.c
lib/init.c
lib/internal.h
lib/mmio-ports.c
lib/pci.h
lib/sylixos-device.c
pcilib.man

Lot of non-x86 platforms also support Intel Type 1 mechanism. x86 IO ports
CF8 and CFC are on these platforms mapped into standard memory space.
Address mapping itself is platform or board specific and there is no
default value.
Lot of ARM boards with multiple PCIe controllers are multi-domain and each
PCI domain has its own CF8/CFC (address/data) registers mapped into memory
space.
Add new mmio-conf1 backend which access CF8/CFC ports via MMIO and define
new config option mmio-conf1.addrs which specify list of address/data
register pairs in memory space for each PCI domain. Format of this option
is: 0xaddr1/0xdata1,0xaddr2/0xdata2,...

libpci: Add Intel Type 1 implementation for memory mapped systems

---

lib/init.c
lib/internal.h
lib/mmio-ports.c
lib/pci.h
pcilib.man

Extended method allows to access all PCIe registers, including extended registers starting at 0x100 offset. This method uses 4 reserved buts above bus bits for PCIe registers. On ARM platforms it is very common for PCIe controllers. Like standard method, it needs to be properly configured.

libpci: mmio-ports: Add Extended PCIe Intel Type 1 access method

---

lib/mmio-ports.c

On 64-bit non-LLP64 systems is type long 64-bit. On 32-bit and 64-bit LLP64 systems is type long only 32-bit. But readl() and writel() functions works with 32-bit PCI word. Fix it for non-LLP64 systems by using type u32.

libpci: mmio-ports: Fix support for 64-bit non-LLP64 systems

---

lib/init.c
lib/internal.h
lib/win32-cfgmgr32.c
pcilib.man

Extend win32-cfgmgr32 backend and add a new option win32.cfgmethod for specifying other backend for accessing PCI config space. There are more config space access methods available on Windows and each is working only sometimes (either requires special privileges or special setup).
So by default try to choose the first working one via order defined in pci probe_sequence[] array. If none is available then emulate PCI config space like before this change.
Function pci_init_v35() is extended and renamed to pci_init_internal() to optionally do not throw errors and allow to specify one access method which will be skipped in AUTO mode. This is used to prevent choosing win32-cfgmgr32 as config space access method for win32-cfgmgr32.

libpci: win32-cfgmgr32: Add support for accessing config space via other backend

---

lib/Makefile
lib/configure
lib/ecam.c
lib/init.c
lib/internal.h
lib/pci.h
pcilib.man

This is a new direct hardware access method via PCIe ECAM (Enhanced Configuration Access Mechanism). It is available on all PCIe-compliant hardware. Requires root privileges and access to physical memory.
ECAM mapping can be specified manually via a new ecam.addrs parameter or can be read from ACPI MCFG table. ACPI MCFG table can be located in the system or read from x86 BIOS memory.

libpci: Add PCIe ECAM access method

---

Makefile

When cross-compile, we should use specific strip instead of default /usr/bin/strip.
reference:https://man7.org/linux/man-pages/man1/install.1.html
Otherwise, when executing:
```
make HOST=aarcj64-none-linux-gnu CROSS_COMPILE=aarch64-none-linux-gnu- &&\
make HOST=aarcj64-none-linux-gnu CROSS_COMPILE=aarch64-none-linux-gnu- DESTDIR=~/test install
```
output:
```
install -c -m 755 -s lspci /root/workspace/pciutils/install/usr/local/bin
strip: Unable to recognise the format of the input file `/root/workspace/pciutils/install/usr/local/bin/lspci'
install: strip process terminated abnormally
make: *** [Makefile:151: install] Error 1
```

Makefile: change STRIP to '--strip-program' when cross-compile

---

ls-caps-vendor.c

Given that PCI VFs are expected to have a vendor and device ID of 0xffff, when examining vendor capabilities use the mangled vendor and device IDs (typically copied from the PF) rather than those read from the VF configuration space.

RFC: lspci: Use mangled vendor/device ID when examining vendor caps

---

lib/header.h

The error bit is specified by the 2nd (zero indexed) bit in the status register, so the respective bit value is 4 (PCI Base Spec 6.0.1). Let's fix that up.

lib: fixup DOE status register bit

---

lib/header.h
ls-ecaps.c

PCie Gen5 becoming more and more popular.
Let's add header parser for  'Physical Layer 32.0 GT/s Extended Capability Header'

Add support for 32.0 GT/s header

---

lib/sysfs.c

```
sysfs.c: In function 'sysfs_read_vpd':
sysfs.c:569:43: warning: unused parameter 'd' [-Wunused-parameter]
static int sysfs_read_vpd(struct pci_dev *d, int pos, byte *buf, int len)
^
sysfs.c:569:50: warning: unused parameter 'pos' [-Wunused-parameter]
static int sysfs_read_vpd(struct pci_dev *d, int pos, byte *buf, int len)
^~~
sysfs.c:569:61: warning: unused parameter 'buf' [-Wunused-parameter]
static int sysfs_read_vpd(struct pci_dev *d, int pos, byte *buf, int len)
^~~
sysfs.c:569:70: warning: unused parameter 'len' [-Wunused-parameter]
static int sysfs_read_vpd(struct pci_dev *d, int pos, byte *buf, int len)
^~~
```

Fix compile warnings about unused variables

---

README
lib/configure
lib/i386-io-access.h
lib/i386-io-beos.h
lib/i386-io-cygwin.h
lib/i386-io-djgpp.h
lib/i386-io-haiku.h
lib/i386-io-hurd.h
lib/i386-io-linux.h
lib/i386-io-openbsd.h
lib/i386-io-sunos.h
lib/i386-io-windows.h
lib/i386-ports.c

This commit adds support for `i386-ports` in OpenBSD. I added this primarily for use with `flashrom`, allowing many more chipsets to be supported.
On OpenBSD, it looks like the arguments to `in` / `out` are reversed. I'm open to suggestions for a better way to handle this, optimally, without touching `lib/i386-ports.c`. I don't write in C often, so this was the quickest way to solve the issue.

i386-ports: Add support for OpenBSD

---

lib/configure

After this, `lspci -q` works as expected on Haiku beta4.

Haiku: fix build with DNS=yes.

---

lib/header.h
ls-ecaps.c

Extend decode support for more fields for AER CE and UE status prior to PCIe r6.0.

ls-ecaps: extend decode support for more fields for AER CE and UE status

---

lib/dump.c

The SPDK VMD driver assigns domains for the devices behind a VMD by concatenating bus/device/function of the VMD, each on a separate byte. For instance, a device behind a VMD with an address of 5d:05.5 would be assigned domain 5d0505.

dump: allow 6-digit domains

---

lib/pci.h
lib/sysfs.c
ls-caps.c
lspci.c

CXL devices are extensions of PCIe. Therefore, from CXL2.0 onwards, the link status can be output in the same way as traditional PCIe.
However, unlike devices from CXL2.0 onwards, CXL1.1 requires a different method to obtain the link status from traditional PCIe.
This is because the link status of the CXL1.1 device is not mapped in the configuration space (as per cxl3.0 specification 8.1).
Instead, the configuration space containing the link status is mapped to the memory mapped register region (as per cxl3.0 specification 8.2, Table 8-18). 
Therefore, the current lspci has a problem where it does not display the link status of the CXL1.1 device. 
Solve these issues with sysfs attributes to export the status registers hidden in the RCRB.
We are currently adding a feature to the Linux …

Add display function for cxl1.1 device link status information.

---

lib/header.h
ls-ecaps.c
setpci.c

Added register field decodes in lspci verbose output for the following extended capability registers:
- Physical Layer 16 GT/s
- Physical Layer 32 GT/s
- Physical Layer 64 GT/s
Also added missing register names to setpci for these registers.

lspci: Added decodes for Physical Layer 16/32/64 extended capabilities registers
